# Generated by Django 2.1.1 on 2018-09-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instagramApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='name',
        ),
        migrations.AlterField(
            model_name='instagram',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
