# Generated by Django 2.1.1 on 2018-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instagramApp', '0003_auto_20180912_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='biograpy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='fullName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='isPrivate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='mediaCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='img/profile'),
        ),
    ]
