# Generated by Django 2.1.1 on 2018-10-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instagramApp', '0004_auto_20180912_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='followerList',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='biograpy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='followings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='fullName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='isPrivate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='mediaCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='profilePicture',
            field=models.ImageField(blank=True, default='img/temp.jpg', upload_to='img/profile'),
        ),
    ]
