# Generated by Django 2.1.1 on 2018-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instagramApp', '0005_auto_20181028_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='followerList',
        ),
        migrations.AddField(
            model_name='instagram',
            name='followerList',
            field=models.ManyToManyField(related_name='_instagram_followerList_+', to='instagramApp.instagram'),
        ),
    ]
